Qualty cade challenge
haroldmud/quality-code-challenge pull request #1
Opened 2023-05-25 15:13 UTC by haroldmud

2023-05-25 15:39 UTC, clever-cr approved these changes

2023-05-25 15:44 UTC, IbrahimBagalwa requested changes
Great Job @haroldmud; 
I left few comment to improve the base code

2023-05-25 15:44 UTC, IbrahimBagalwa commented on NumberFormat.js
> +};
you could use the new Es6 Syntax
```js
const numberFormat = (number)=>number.toLocaleString()
```

2023-05-25 15:44 UTC, IbrahimBagalwa commented on Roman_Numerals_Decoder.jst
> +}
Can you change the extension of your file because this is not a valid extension file.

2023-05-25 15:44 UTC, IbrahimBagalwa commented on string_addition.js
> +}
Could you use ES6 here to make it easy.
```js
const joinStrings=(string1, string2)=> `${string1} ${string2}`

2023-05-30 15:38 UTC, musayann commented on Create Phone Number
> +  }
use array functions

2023-05-30 15:42 UTC, IbrahimBagalwa commented on roundRobin
> +}
Here as well change the extension file

2024-01-24 09:38 UTC, merged